name: npyodbc tests
on: [push, pull_request]
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11']
        numpy-version: ['latest', '1.24.4']
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install sqlite
        run: |
          sudo apt update
          sudo apt install -y sqlite3 unixodbc-dev libsqliteodbc

      - name: Install npyodbc
        run: |
          pip install .[test]

      - name: Install target numpy version
        if: matrix.numpy-version != 'latest'
        run: |
          set -xe
          pip install numpy==${{ matrix.numpy-version }}
          pip list

      - name: Run Numpy Tests
        run: |
          set -xe
          pytest -vv tests/test_numpy.py
